// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Dinhom_pair_c
NumericVector Dinhom_pair_c(int from, int to, NumericMatrix x, NumericMatrix bbox, NumericVector lambda, IntegerVector type, NumericVector bdist, NumericVector rho0, NumericVector r, int nmarks);
RcppExport SEXP sseg_Dinhom_pair_c(SEXP fromSEXP, SEXP toSEXP, SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP typeSEXP, SEXP bdistSEXP, SEXP rho0SEXP, SEXP rSEXP, SEXP nmarksSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nmarks(nmarksSEXP);
    __result = Rcpp::wrap(Dinhom_pair_c(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks));
    return __result;
END_RCPP
}
// Dinhom_pair_2_c
NumericVector Dinhom_pair_2_c(int from, int to, NumericMatrix x, NumericMatrix bbox, NumericVector lambda, IntegerVector type, NumericVector bdist, NumericVector rho0, NumericVector r, int nmarks);
RcppExport SEXP sseg_Dinhom_pair_2_c(SEXP fromSEXP, SEXP toSEXP, SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP typeSEXP, SEXP bdistSEXP, SEXP rho0SEXP, SEXP rSEXP, SEXP nmarksSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nmarks(nmarksSEXP);
    __result = Rcpp::wrap(Dinhom_pair_2_c(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks));
    return __result;
END_RCPP
}
// Dinhom_pair_graph_c
NumericVector Dinhom_pair_graph_c(int from, int to, NumericMatrix x, NumericMatrix bbox, NumericVector lambda, IntegerVector type, NumericVector bdist, NumericVector r, int nmarks);
RcppExport SEXP sseg_Dinhom_pair_graph_c(SEXP fromSEXP, SEXP toSEXP, SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP typeSEXP, SEXP bdistSEXP, SEXP rSEXP, SEXP nmarksSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nmarks(nmarksSEXP);
    __result = Rcpp::wrap(Dinhom_pair_graph_c(from, to, x, bbox, lambda, type, bdist, r, nmarks));
    return __result;
END_RCPP
}
// Dinhom_c
NumericVector Dinhom_c(NumericMatrix x, NumericMatrix bbox, NumericVector lambda, NumericVector bdist, double inf_int, NumericVector r);
RcppExport SEXP sseg_Dinhom_c(SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP bdistSEXP, SEXP inf_intSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< double >::type inf_int(inf_intSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    __result = Rcpp::wrap(Dinhom_c(x, bbox, lambda, bdist, inf_int, r));
    return __result;
END_RCPP
}
// graph_c
List graph_c(NumericMatrix x, NumericMatrix bb, int gtype, NumericVector gpar, double MaxR);
RcppExport SEXP sseg_graph_c(SEXP xSEXP, SEXP bbSEXP, SEXP gtypeSEXP, SEXP gparSEXP, SEXP MaxRSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bb(bbSEXP);
    Rcpp::traits::input_parameter< int >::type gtype(gtypeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gpar(gparSEXP);
    Rcpp::traits::input_parameter< double >::type MaxR(MaxRSEXP);
    __result = Rcpp::wrap(graph_c(x, bb, gtype, gpar, MaxR));
    return __result;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP sseg_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
