# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Dinhom_pair_c <- function(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks) {
    .Call('sseg_Dinhom_pair_c', PACKAGE = 'sseg', from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks)
}

Dinhom_pair_2_c <- function(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks) {
    .Call('sseg_Dinhom_pair_2_c', PACKAGE = 'sseg', from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks)
}

Dinhom_pair_graph_c <- function(from, to, x, bbox, lambda, type, bdist, r, nmarks) {
    .Call('sseg_Dinhom_pair_graph_c', PACKAGE = 'sseg', from, to, x, bbox, lambda, type, bdist, r, nmarks)
}

Dinhom_c <- function(x, bbox, lambda, bdist, inf_int, r) {
    .Call('sseg_Dinhom_c', PACKAGE = 'sseg', x, bbox, lambda, bdist, inf_int, r)
}

graph_c <- function(x, bb, gtype = 1L, gpar = 0L, MaxR = 0) {
    .Call('sseg_graph_c', PACKAGE = 'sseg', x, bb, gtype, gpar, MaxR)
}

rcpp_hello <- function() {
    .Call('sseg_rcpp_hello', PACKAGE = 'sseg')
}

